# Generated by Django 3.0.1 on 2019-12-30 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('done', models.BooleanField(default=False)),
                ('deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
